version: 2

multi-ecosystem-groups:
  weekly-maintenance:
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "Europe/Istanbul"
    labels:
      - "dependencies"

updates:
  - package-ecosystem: "pub"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-maintenance"

  - package-ecosystem: "gradle"
    directory: "/android"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-maintenance"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns:
      - "*"
    multi-ecosystem-group: "weekly-maintenance"
